### ISSUE TITLE
No menu on explore/gallery page when less then 768 pixels wide

### ISSUE THREAD

**Issue by scootergrisen** [mozilla/webmaker.org#1241] opened 2015-02-16 13:47 UTC
Go to https://webmaker.org/en-US/explore make the browser window below 768 pixels wide.

The menu will not be there and althougt there is a box in the top right corner nothing happens when you click it, so you can see the menu or use it on the page.

**Comment by ScottDowne** [comment] 2015-02-23 18:07
This looks like a duplicate of #1176 to me.

**Closed by ScottDowne** 2015-02-23 18:07 UTC
