### ISSUE TITLE
Flipped eye hexagon text feels tight

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker.org#1164] opened 2015-01-21 22:29 UTC
![image](https://cloud.githubusercontent.com/assets/25212/5846618/e0c5ef4a-a179-11e4-8f9a-8127ef5e4947.png)

"Privacy Matters" feels too close to the top edges of the hexagon, could we move it down a tiny bit?

@iamjessklein

**Comment by iamjessklein** [comment] 2015-01-22 01:52
:+1: agreed, this is a dupe of #1148

**Closed by iamjessklein** 2015-01-22 01:52 UTC
Labels: quality
