### ISSUE TITLE
From 1261 - I get "enter your phone number" in tablet

### ISSUE THREAD

**Issue by errietta** [mozilla/webmaker.org#1311] opened 2015-02-24 21:00 UTC
I have an android tablet - Samsung Galaxy Tab 3 running android 4.4.2. I go to https://webmaker.mofostaging.net/app on firefox (Mozilla/5.0 (Android; Tablet; rv:35.0) Gecko/35.0 Firefox/35.0)and click 'get app'. I expect to get a download, but instead am told (like the desktop version) to enter a phone number.

This only happens in landscape mode, because the resolution is quite wide there and it thinks I'm on a desktop. We need another way of telling if it's  a desktop or not.

**Comment by cadecairos** [comment] 2015-02-24 21:04
Duplicate of #1306

**Closed by cadecairos** 2015-02-24 21:04 UTC
