### ISSUE TITLE
Install page: download button results in infinite loop

### ISSUE THREAD

**Issue by gesa** [mozilla/webmaker.org#1301] opened 2015-02-24 18:41 UTC
QA-ing for #1261

*OS:* Mac OS X
*Browser:* Chrome 40 and Firefox (35 & 37)

**Repro Steps:**
1. Click "download webmaker"

**Expected:** Not entirely certain
**Actual:** Browser loads a blue page with "undefined" in the middle, then reloads a page identical to the original download page, but hosted on heroku

**Comment by cadecairos** [comment] 2015-02-24 19:19
This is a dupe of #1305

**Closed by cadecairos** 2015-02-24 19:19 UTC
Labels: bug, critical
