### ISSUE TITLE
Downloading screen should tell people what to do next

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker.org#1291] opened 2015-02-24 17:42 UTC
On Android, after downloading the app, the screen looks like:

![2015-02-24 17 40 33](https://cloud.githubusercontent.com/assets/51278/6355223/44849ac8-bc09-11e4-9fc9-077edb312211.png)

If someone has never installed from a downloaded APK before, knowing that one has to scroll from the top and tap on the "Download Complete" notification may not be obvious.

How about adding some language like:

"Once the app has finished downloading, look in your notifications and tap on the notification to finish the installation process"?

(note: should really change APK name, but i know that's been filed already)

**Comment by cadecairos** [comment] 2015-02-24 19:28
probably a dupe of mozilla/webmaker-app#1257

**Comment by secretrobotron** [comment] 2015-02-24 22:31
Indeed a dupe! Thanks friends.

**Closed by secretrobotron** 2015-02-24 22:31 UTC
Labels: enhancement
