### ISSUE TITLE
[Android] Start app, pick "start from scratch", then try to get back to the main menu.

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker.org#1300] opened 2015-02-24 18:37 UTC
You can't. The tucan refuses to back down.

**Comment by k88hudson** [comment] 2015-02-24 18:46
This is a dupe of mozilla/webmaker-app/#1304

Also, please file QA bugs related to webmaker-app in that repo if possible :+1:

**Closed by k88hudson** 2015-02-24 18:46 UTC
Labels: bug, critical

**Comment by Pomax** [comment] 2015-02-24 18:55
I could have sworn that's where I was. weird wrong-repo filing.
