### ISSUE TITLE
Fix spacing between field and button on Success screen (onboarding)

### ISSUE THREAD

**Issue by cassiemc** [mozilla/webmaker.org#1110] opened 2015-01-16 21:22 UTC
![nospace](https://cloud.githubusercontent.com/assets/1186326/5784622/d96f40f2-9d9b-11e4-8afa-8d589e36f3ee.jpg)

Using FF 35 on mac.

**Comment by xmatthewx** [comment] 2015-01-16 21:27
duplicate of #1103

**Closed by xmatthewx** 2015-01-16 21:27 UTC
