### ISSUE TITLE
"Login to apply" button doesn't appear during page load

### ISSUE THREAD

**Issue by simonwex** [mozilla/webmaker.org#1233] opened 2015-02-12 21:08 UTC
When visiting https://webmaker.org/badges/design-maker, the "Login to apply is missing":

![image](https://cloud.githubusercontent.com/assets/25260/6177026/3501fa82-b2b8-11e4-8a7b-aa641fbeedb0.png)

If you go to another tab and return, it appears. It seems it's in conjunction with the following output in the console:
```POST https://webmaker.org/verify```

Its triumphant return:
![image](https://cloud.githubusercontent.com/assets/25260/6177048/608874f6-b2b8-11e4-81a0-2d56ace43a86.png)

**Comment by simonwex** [comment] 2015-02-12 21:10
might be related to #1232

**Comment by ScottDowne** [comment] 2015-02-12 22:44
I can confirm that this bug is setting up the event listeners for on login and on logout after login has already fired its event.

I'm not yet sure if that's the cause of #1232, it might be.

**Comment by ScottDowne** [comment] 2015-02-12 22:50
Might be the fix?

https://github.com/mozilla/webmaker.org/pull/1235

**Comment by ScottDowne** [comment] 2015-02-18 19:16
Yup, fixed in #1235

**Closed by ScottDowne** 2015-02-18 19:16 UTC
Labels: bug, critical
