### ISSUE TITLE
"Learn More" button "pressed" state is inconsistent with button in blue area above.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker.org#1162] opened 2015-01-21 22:25 UTC
When the button is in the "active" or pressed down state, it moves up slightly. It should move down slightly to look 'depressed'.

![image](https://cloud.githubusercontent.com/assets/25212/5846550/4f734f92-a179-11e4-8de4-9ecb3fc4fbca.png)

@iamjessklein

**Comment by iamjessklein** [comment] 2015-01-22 01:49
:+1:  this is a dupe of #1150

**Closed by iamjessklein** 2015-01-22 01:49 UTC
Labels: quality
